-- PostgreSQL schema (Supabase) — apply thông qua: npm run db:migrate
-- ID dùng GENERATED BY DEFAULT AS IDENTITY để giữ nguyên id khi migrate dữ liệu cũ.

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  size TEXT NOT NULL DEFAULT '',
  material TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  supplier TEXT NOT NULL DEFAULT '',
  retail_price BIGINT NOT NULL,
  discount_tp DOUBLE PRECISION,
  discount_b2b DOUBLE PRECISION,
  note TEXT NOT NULL DEFAULT '',
  is_hot INTEGER NOT NULL DEFAULT 0,
  image_path TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '',
  area_per_tile_m2 DOUBLE PRECISION,
  trade_price BIGINT,
  b2b_price BIGINT,
  surface TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT 'm²',
  internal_code TEXT NOT NULL DEFAULT '',
  internal_codes TEXT NOT NULL DEFAULT '',
  collections TEXT NOT NULL DEFAULT '',
  shape TEXT NOT NULL DEFAULT '',
  texture TEXT NOT NULL DEFAULT ''
);

-- Atomically migrate legacy product meanings.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'products' AND column_name = 'finish_effect')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'products' AND column_name = 'supplier') THEN
    ALTER TABLE products RENAME COLUMN collections TO supplier;
    ALTER TABLE products RENAME COLUMN finish_effect TO collections;
  END IF;
END $$;

-- Khối lượng đóng gói (Kg/thùng) & Cột Texture (Hiệu ứng vân) — idempotent cho DB đã tạo trước đó.
ALTER TABLE products ADD COLUMN IF NOT EXISTS area_per_tile_m2 DOUBLE PRECISION;
-- Bỏ khái niệm thùng/packing khỏi products — diện tích 1 viên chuẩn ở area_per_tile_m2.
ALTER TABLE products DROP COLUMN IF EXISTS packing;
ALTER TABLE products DROP COLUMN IF EXISTS packing_m2;
ALTER TABLE products DROP COLUMN IF EXISTS packing_pcs;
ALTER TABLE products DROP COLUMN IF EXISTS packing_kg;
ALTER TABLE products ADD COLUMN IF NOT EXISTS texture TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_products_texture ON products(texture);

CREATE UNIQUE INDEX IF NOT EXISTS ux_products_code ON products(code);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_category_lower ON products(LOWER(category));

CREATE TABLE IF NOT EXISTS product_internal_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  internal_code TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_product_internal_codes_code ON product_internal_codes(internal_code);
CREATE INDEX IF NOT EXISTS idx_product_internal_codes_product ON product_internal_codes(product_id);

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  internal_code TEXT NOT NULL REFERENCES product_internal_codes(internal_code) ON DELETE CASCADE,
  stock_location TEXT NOT NULL,
  quantity_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_loc ON inventory(internal_code, stock_location);
CREATE INDEX IF NOT EXISTS idx_inventory_internal_code ON inventory(internal_code);

-- Chuyển kho Q9 → kho Bình Chánh (KHOBC), 09/2026 (file MISA đổi tên kho).
-- Idempotent + chống double-count:
--  * Đã có dòng KHOBC (đã import file MISA mới — file cộng dồn cả nhãn KHOQ9
--    vào KHOBC khi import): dòng KHOQ9 cũ chỉ là dữ liệu lỗi thời → xoá sạch.
--  * Chưa có dòng KHOBC (chưa import sau đổi tên): KHOQ9 là dữ liệu hiện hành
--    → chỉ đổi nhãn KHOQ9 → KHOBC, giữ nguyên số lượng.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM inventory WHERE stock_location = 'KHOBC') THEN
    DELETE FROM inventory WHERE stock_location = 'KHOQ9';
  ELSE
    UPDATE inventory SET stock_location = 'KHOBC' WHERE stock_location = 'KHOQ9';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_username ON users(username);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT '',
  last_seen_at TEXT,
  user_agent TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  region TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'consulting',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  owner_id BIGINT REFERENCES users(id),
  email TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  short_name TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_customers_owner ON customers(owner_id);

CREATE TABLE IF NOT EXISTS quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'draft',
  notes TEXT NOT NULL DEFAULT '',
  discount_type TEXT NOT NULL DEFAULT 'none',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  prices_include_vat INTEGER NOT NULL DEFAULT 0,
  shipping_fee INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_quotes_code ON quotes(code);
CREATE INDEX IF NOT EXISTS idx_quotes_customer ON quotes(customer_id);

CREATE TABLE IF NOT EXISTS quote_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id BIGINT NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  product_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  size TEXT NOT NULL DEFAULT '',
  material TEXT NOT NULL DEFAULT '',
  packing TEXT NOT NULL DEFAULT '',
  quantity_m2 DOUBLE PRECISION NOT NULL DEFAULT 0,
  retail_price BIGINT NOT NULL,
  discount_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
  unit_price BIGINT NOT NULL,
  area TEXT NOT NULL DEFAULT '',
  line_total BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_quote_items_quote ON quote_items(quote_id);
CREATE INDEX IF NOT EXISTS idx_quote_items_product ON quote_items(product_id);
-- Idempotent cho DB tạo từ schema trước đó (live DB đã có từ migration cũ).
ALTER TABLE quote_items ADD COLUMN IF NOT EXISTS material TEXT NOT NULL DEFAULT '';
ALTER TABLE quote_items ADD COLUMN IF NOT EXISTS packing TEXT NOT NULL DEFAULT '';
-- Dọn cột thừa (không được code dùng): origin → marker đã có product_id NOT NULL.
ALTER TABLE quote_items DROP COLUMN IF EXISTS origin;
-- Cột ảnh/bề mặt snapshot từ feature cũ bị revert — code không dùng.
ALTER TABLE quote_items DROP COLUMN IF EXISTS image_path;
ALTER TABLE quote_items DROP COLUMN IF EXISTS surface;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  quote_id BIGINT REFERENCES quotes(id) ON DELETE SET NULL,
  amount BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'preparing',
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  shipping_fee INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_orders_code ON orders(code);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  amount BIGINT NOT NULL,
  paid_at TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_payments_customer ON payments(customer_id);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  author TEXT NOT NULL DEFAULT 'Showroom',
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT '',
  author_user_id BIGINT REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_notes_customer ON notes(customer_id);
CREATE INDEX IF NOT EXISTS idx_notes_created ON notes(created_at DESC);

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_primary INTEGER NOT NULL DEFAULT 0,
  caption TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT 'normal',
  is_public INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT ''
);
-- Phân loại ảnh: 'map' (ảnh gạch — tối đa 1/SP), 'concept' (ảnh bối cảnh), 'normal' (không gán).
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'normal';
-- Mô tả chi tiết không gian/bối cảnh thị giác do AI Vision sinh ra
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS ai_description TEXT NOT NULL DEFAULT '';
-- Trạng thái hiển thị công khai trên Landing Page Lookbook (1 = hiện, 0 = ẩn)
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS is_public INTEGER NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS idx_product_images_concept_public ON product_images(kind, is_public);
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_images_unique_path ON product_images(product_id, path);
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_images_imported_unique_path
  ON product_images (product_id, path) WHERE path LIKE '/products/imported/%';
CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images(product_id);
-- Chỉ 1 ảnh MAP mỗi sản phẩm.
CREATE UNIQUE INDEX IF NOT EXISTS ux_product_images_one_map
  ON product_images (product_id) WHERE kind = 'map';
 
-- Bối cảnh phòng của ảnh concept. room_slug dùng chung vocabulary ở src/lib/types.ts:
-- SPACE_TYPES là các slug phòng chuẩn, IMAGE_ROOM_TAGS là danh sách đầy đủ (thêm 3 slug
-- image-only office_workspace/other/unknown chỉ dùng cho ảnh, không có trong SPACE_TYPES).
CREATE TABLE IF NOT EXISTS product_image_room_tags (
  product_image_id BIGINT NOT NULL REFERENCES product_images(id) ON DELETE CASCADE,
  room_slug TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'manual',
  confidence DOUBLE PRECISION,
  model TEXT NOT NULL DEFAULT '',
  model_version TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (product_image_id, room_slug)
);
-- Bộ review thẻ phòng (review_status/reviewed_by/reviewed_at) chưa từng được xây:
-- mọi INSERT ghi cứng 'accepted' (1435/1435 dòng), reviewed_by/reviewed_at luôn NULL → bỏ.
ALTER TABLE product_image_room_tags DROP COLUMN IF EXISTS review_status;
ALTER TABLE product_image_room_tags DROP COLUMN IF EXISTS reviewed_by;
ALTER TABLE product_image_room_tags DROP COLUMN IF EXISTS reviewed_at;
CREATE INDEX IF NOT EXISTS idx_product_image_room_tags_slug
  ON product_image_room_tags(room_slug);

-- Registry ảnh `image_assets` + Delayed GC đã bị CẮT BỎ (2026-09-24).
-- Nguồn sự thật duy nhất cho "ảnh đang dùng ở đâu" là Image Reference Resolver
-- (`src/db/image-references.server.ts` — 5 bảng ref, tính live mỗi lần đọc).
-- Không xoá physical file tự động: gỡ ảnh khỏi nơi dùng chỉ làm nó hết tham
-- chiếu; file vẫn nằm trong storage cho tới khi xoá thủ công ở /luu-tru.
DROP TABLE IF EXISTS image_assets CASCADE;

CREATE TABLE IF NOT EXISTS customer_product_samples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  sample_sent INTEGER NOT NULL DEFAULT 0,
  sample_sent_at TEXT,
  source TEXT NOT NULL DEFAULT 'manual',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_customer_product_samples ON customer_product_samples(customer_id, product_id);

CREATE TABLE IF NOT EXISTS customer_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  code TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  version TEXT NOT NULL DEFAULT '01'
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_customer_mappings_code ON customer_mappings(code);
CREATE INDEX IF NOT EXISTS idx_customer_mappings_customer_updated ON customer_mappings(customer_id, updated_at DESC, id DESC);
-- Căn cứ giá in trên đề xuất: 'retail' | 'tp' | 'b2b'.
ALTER TABLE customer_mappings ADD COLUMN IF NOT EXISTS price_basis TEXT NOT NULL DEFAULT 'retail';

CREATE TABLE IF NOT EXISTS customer_mapping_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mapping_id BIGINT NOT NULL REFERENCES customer_mappings(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  description TEXT NOT NULL DEFAULT '',
  size TEXT NOT NULL DEFAULT '',
  product_id BIGINT REFERENCES products(id),
  image_path TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  custom_product_code TEXT NOT NULL DEFAULT '',
  custom_product_name TEXT NOT NULL DEFAULT '',
  custom_product_size TEXT NOT NULL DEFAULT '',
  custom_product_surface TEXT NOT NULL DEFAULT '',
  custom_product_retail_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  custom_product_image_path TEXT NOT NULL DEFAULT '',
  area_group_key TEXT NOT NULL DEFAULT '',
  area_description TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_mapping_items_mapping ON customer_mapping_items(mapping_id);
-- NULL = tự tính theo customer_mappings.price_basis; có số = giá chốt tay.
ALTER TABLE customer_mapping_items ADD COLUMN IF NOT EXISTS price_override DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS customer_mapping_quote_links (
  mapping_id BIGINT NOT NULL REFERENCES customer_mappings(id) ON DELETE CASCADE,
  quote_id BIGINT NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (mapping_id, quote_id)
);
CREATE INDEX IF NOT EXISTS idx_mapping_quote_links_quote ON customer_mapping_quote_links(quote_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  username TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL DEFAULT '',
  entity_id BIGINT,
  summary TEXT NOT NULL DEFAULT '',
  meta_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);

-- ─── Landing page (ads) ─────────────────────────────────────
-- Cờ xuất bản công khai cho catalog LP. Mặc định 0 = không public.
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_public INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS featured_rank INTEGER;
CREATE INDEX IF NOT EXISTS idx_products_public
  ON products(is_public, featured_rank, id);

-- Lead thô từ landing page. KHÔNG ghi thẳng vào customers: ads traffic
-- submit trùng là bình thường, còn customers bắt buộc SĐT không trùng
-- + owner_id. Staff duyệt trong CRM rồi mới convert.
CREATE TABLE IF NOT EXISTS lp_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  -- SĐT chuẩn hoá (0xxxxxxxxx) để gom trùng mà không chặn submit
  phone_norm TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  -- Nhu cầu: dòng gạch khách chọn (Gạch thẻ / Mosaic / Bông / Ốp lát)
  need TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  -- Biến thể LP đã submit (slug), để so hiệu quả từng bản
  lp_slug TEXT NOT NULL DEFAULT '',
  -- Mã gạch khách tự lưu vào shortlist (CSV) — sales biết trước khách
  -- thích gì thay vì gọi hỏi lại từ đầu.
  shortlist_codes TEXT NOT NULL DEFAULT '',
  -- new | contacted | converted | spam
  status TEXT NOT NULL DEFAULT 'new',
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  utm_source TEXT NOT NULL DEFAULT '',
  utm_medium TEXT NOT NULL DEFAULT '',
  utm_campaign TEXT NOT NULL DEFAULT '',
  utm_content TEXT NOT NULL DEFAULT '',
  utm_term TEXT NOT NULL DEFAULT '',
  referrer TEXT NOT NULL DEFAULT '',
  landing_path TEXT NOT NULL DEFAULT '',
  -- Hash IP (không lưu IP thô) — chỉ dùng chống spam
  ip_hash TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT '',
  consent_marketing INTEGER NOT NULL DEFAULT 0,
  consent_at TEXT NOT NULL DEFAULT '',
  handled_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  handled_at TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT ''
);
-- Brief kiến trúc sư (form dài trên landing). Thêm dạng ALTER để DB đang
-- chạy nâng cấp được mà không mất dữ liệu lead cũ.
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS studio TEXT NOT NULL DEFAULT '';
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS project_type TEXT NOT NULL DEFAULT '';
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS project_stage TEXT NOT NULL DEFAULT '';
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS project_name TEXT NOT NULL DEFAULT '';
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS area TEXT NOT NULL DEFAULT '';
-- Tên file khách chọn đính kèm (CSV). CHỈ là tên — file chưa được upload,
-- endpoint upload công khai chưa mở (xem docs). Sales chủ động xin lại file.
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS attachment_names TEXT NOT NULL DEFAULT '';
-- Nguồn form: 'lp' (landing) | 'library-gate' (mở Thư viện mã gạch)
--           | 'google-unlock' (đăng nhập Google để mở khoá nội dung)
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS form_kind TEXT NOT NULL DEFAULT 'lp';
-- JSON chi tiết ngữ cảnh shortlist (mã gạch + bối cảnh không gian + vị trí ghim)
ALTER TABLE lp_leads ADD COLUMN IF NOT EXISTS shortlist_details TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_lp_leads_created ON lp_leads(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_lp_leads_status ON lp_leads(status);
CREATE INDEX IF NOT EXISTS idx_lp_leads_phone_norm ON lp_leads(phone_norm);
CREATE INDEX IF NOT EXISTS idx_lp_leads_slug ON lp_leads(lp_slug);

-- Rate limit endpoint public (fixed window, key = ip_hash + slug).
-- 5 lượt / 10 phút / IP / slug.
CREATE TABLE IF NOT EXISTS lp_rate_limits (
  bucket TEXT PRIMARY KEY,
  hits INTEGER NOT NULL DEFAULT 0,
  window_start TEXT NOT NULL DEFAULT ''
);

-- ─── Public Landing Users & Sessions (Supabase Google OAuth) ─
CREATE TABLE IF NOT EXISTS public_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supabase_id TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL DEFAULT '',
  raw_user_meta_data JSONB,
  first_seen_at TEXT NOT NULL DEFAULT '',
  last_seen_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_public_users_email ON public_users(email);

CREATE TABLE IF NOT EXISTS public_sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public_users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_public_sessions_user ON public_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_public_sessions_expires ON public_sessions(expires_at);

-- Cài đặt cấu hình hiển thị Landing Page (Hero Banner, v.v.)
CREATE TABLE IF NOT EXISTS lp_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT ''
);
-- ─── Row Level Security ─────────────────────────────────────
-- Dọn index trùng: public_users_supabase_id_key (UNIQUE) đã phủ cùng cột.
DROP INDEX IF EXISTS idx_public_users_supabase;
-- CRM truy cập Postgres qua DATABASE_URL (role server / bypass RLS).
-- Browser không dùng Supabase PostgREST + anon key cho bảng CRM.
-- Bật RLS trên mọi bảng public, KHÔNG tạo policy anon/authenticated
-- → chặn đọc/ghi/xóa qua REST công khai; app server vẫn hoạt động bình thường.
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT c.relname AS tablename
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'r' -- ordinary tables only
      AND c.relname NOT LIKE 'pg_%'
    ORDER BY c.relname
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', r.tablename);
  END LOOP;
END $$;
