-- PostgreSQL schema (Supabase) — apply thông qua: npm run db:migrate
-- ID dùng GENERATED BY DEFAULT AS IDENTITY để giữ nguyên id khi migrate dữ liệu cũ.

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  size TEXT NOT NULL DEFAULT '',
  material TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  supplier TEXT NOT NULL DEFAULT '',
  retail_price BIGINT NOT NULL,
  discount_tp DOUBLE PRECISION,
  discount_b2b DOUBLE PRECISION,
  note TEXT NOT NULL DEFAULT '',
  is_hot INTEGER NOT NULL DEFAULT 0,
  image_path TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '',
  packing TEXT NOT NULL DEFAULT '',
  packing_m2 DOUBLE PRECISION,
  packing_pcs DOUBLE PRECISION,
  trade_price BIGINT,
  b2b_price BIGINT,
  surface TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT 'm²',
  internal_code TEXT NOT NULL DEFAULT '',
  internal_codes TEXT NOT NULL DEFAULT '',
  collections TEXT NOT NULL DEFAULT '',
  shape TEXT NOT NULL DEFAULT ''
);

-- Atomically migrate legacy product meanings; gallery_collections stays unchanged.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'products' AND column_name = 'finish_effect')
     AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'products' AND column_name = 'supplier') THEN
    ALTER TABLE products RENAME COLUMN collections TO supplier;
    ALTER TABLE products RENAME COLUMN finish_effect TO collections;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_products_code ON products(code);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_category_lower ON products(LOWER(category));

CREATE TABLE IF NOT EXISTS product_internal_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  internal_code TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_product_internal_codes_code ON product_internal_codes(internal_code);
CREATE INDEX IF NOT EXISTS idx_product_internal_codes_product ON product_internal_codes(product_id);

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  internal_code TEXT NOT NULL REFERENCES product_internal_codes(internal_code) ON DELETE CASCADE,
  stock_location TEXT NOT NULL,
  quantity_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_loc ON inventory(internal_code, stock_location);
CREATE INDEX IF NOT EXISTS idx_inventory_internal_code ON inventory(internal_code);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_username ON users(username);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT '',
  last_seen_at TEXT,
  user_agent TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  region TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'consulting',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  owner_id BIGINT REFERENCES users(id),
  email TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  short_name TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_customers_owner ON customers(owner_id);

CREATE TABLE IF NOT EXISTS quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'draft',
  notes TEXT NOT NULL DEFAULT '',
  discount_type TEXT NOT NULL DEFAULT 'none',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  prices_include_vat INTEGER NOT NULL DEFAULT 0,
  shipping_fee INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_quotes_code ON quotes(code);
CREATE INDEX IF NOT EXISTS idx_quotes_customer ON quotes(customer_id);

CREATE TABLE IF NOT EXISTS quote_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id BIGINT NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  product_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  size TEXT NOT NULL DEFAULT '',
  quantity_m2 DOUBLE PRECISION NOT NULL DEFAULT 0,
  retail_price BIGINT NOT NULL,
  discount_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
  unit_price BIGINT NOT NULL,
  area TEXT NOT NULL DEFAULT '',
  line_total BIGINT NOT NULL DEFAULT 0,
  origin TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_quote_items_quote ON quote_items(quote_id);
CREATE INDEX IF NOT EXISTS idx_quote_items_product ON quote_items(product_id);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  quote_id BIGINT REFERENCES quotes(id) ON DELETE SET NULL,
  amount BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'preparing',
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  shipping_fee INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_orders_code ON orders(code);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  amount BIGINT NOT NULL,
  paid_at TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_payments_customer ON payments(customer_id);

CREATE TABLE IF NOT EXISTS notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  author TEXT NOT NULL DEFAULT 'Showroom',
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT '',
  author_user_id BIGINT REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_notes_customer ON notes(customer_id);
CREATE INDEX IF NOT EXISTS idx_notes_created ON notes(created_at DESC);

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_primary INTEGER NOT NULL DEFAULT 0,
  caption TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_images_unique_path ON product_images(product_id, path);
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_images_imported_unique_path
  ON product_images (product_id, path) WHERE path LIKE '/products/imported/%';
CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images(product_id);

CREATE TABLE IF NOT EXISTS gallery_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  cover_path TEXT NOT NULL DEFAULT '',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_gallery_collections_updated ON gallery_collections(updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS gallery_collection_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES gallery_collections(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  product_image_id BIGINT REFERENCES product_images(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product_code TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  caption TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_gallery_collection_items_path ON gallery_collection_items(collection_id, path);
CREATE INDEX IF NOT EXISTS idx_gallery_collection_items_collection ON gallery_collection_items(collection_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_gallery_collection_items_product ON gallery_collection_items(product_id);
CREATE INDEX IF NOT EXISTS idx_gallery_collection_items_path ON gallery_collection_items(path);

CREATE TABLE IF NOT EXISTS customer_product_samples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_code TEXT NOT NULL,
  product_name TEXT NOT NULL,
  sample_sent INTEGER NOT NULL DEFAULT 0,
  sample_sent_at TEXT,
  source TEXT NOT NULL DEFAULT 'manual',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_customer_product_samples ON customer_product_samples(customer_id, product_id);

CREATE TABLE IF NOT EXISTS customer_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  code TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  version TEXT NOT NULL DEFAULT '01'
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_customer_mappings_code ON customer_mappings(code);
CREATE INDEX IF NOT EXISTS idx_customer_mappings_customer_updated ON customer_mappings(customer_id, updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS customer_mapping_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mapping_id BIGINT NOT NULL REFERENCES customer_mappings(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  description TEXT NOT NULL DEFAULT '',
  size TEXT NOT NULL DEFAULT '',
  product_id BIGINT REFERENCES products(id),
  image_path TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  custom_product_code TEXT NOT NULL DEFAULT '',
  custom_product_name TEXT NOT NULL DEFAULT '',
  custom_product_size TEXT NOT NULL DEFAULT '',
  custom_product_surface TEXT NOT NULL DEFAULT '',
  custom_product_retail_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  custom_product_image_path TEXT NOT NULL DEFAULT '',
  area_group_key TEXT NOT NULL DEFAULT '',
  area_description TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_mapping_items_mapping ON customer_mapping_items(mapping_id);

CREATE TABLE IF NOT EXISTS customer_mapping_quote_links (
  mapping_id BIGINT NOT NULL REFERENCES customer_mappings(id) ON DELETE CASCADE,
  quote_id BIGINT NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (mapping_id, quote_id)
);
CREATE INDEX IF NOT EXISTS idx_mapping_quote_links_quote ON customer_mapping_quote_links(quote_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  username TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL DEFAULT '',
  entity_id BIGINT,
  summary TEXT NOT NULL DEFAULT '',
  meta_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);
