/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppTongQuanRouteImport } from './routes/_app.tong-quan'
import { Route as AppThuVienRouteImport } from './routes/_app.thu-vien'
import { Route as AppSanPhamRouteImport } from './routes/_app.san-pham'
import { Route as AppNhatKyRouteImport } from './routes/_app.nhat-ky'
import { Route as AppNguoiDungRouteImport } from './routes/_app.nguoi-dung'
import { Route as AppLuuTruRouteImport } from './routes/_app.luu-tru'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppKhongGianRouteImport } from './routes/_app.khong-gian'
import { Route as AppKhachHangRouteImport } from './routes/_app.khach-hang'
import { Route as AppGhiChuRouteImport } from './routes/_app.ghi-chu'
import { Route as AppCongNoRouteImport } from './routes/_app.cong-no'
import { Route as AppCoHoiRouteImport } from './routes/_app.co-hoi'
import { Route as AppBaoGiaRouteImport } from './routes/_app.bao-gia'
import { Route as AppKhachHangIndexRouteImport } from './routes/_app.khach-hang.index'
import { Route as AppKhachHangCustomerIdRouteImport } from './routes/_app.khach-hang.$customerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTongQuanRoute = AppTongQuanRouteImport.update({
  id: '/tong-quan',
  path: '/tong-quan',
  getParentRoute: () => AppRoute,
} as any)
const AppThuVienRoute = AppThuVienRouteImport.update({
  id: '/thu-vien',
  path: '/thu-vien',
  getParentRoute: () => AppRoute,
} as any)
const AppSanPhamRoute = AppSanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => AppRoute,
} as any)
const AppNhatKyRoute = AppNhatKyRouteImport.update({
  id: '/nhat-ky',
  path: '/nhat-ky',
  getParentRoute: () => AppRoute,
} as any)
const AppNguoiDungRoute = AppNguoiDungRouteImport.update({
  id: '/nguoi-dung',
  path: '/nguoi-dung',
  getParentRoute: () => AppRoute,
} as any)
const AppLuuTruRoute = AppLuuTruRouteImport.update({
  id: '/luu-tru',
  path: '/luu-tru',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppKhongGianRoute = AppKhongGianRouteImport.update({
  id: '/khong-gian',
  path: '/khong-gian',
  getParentRoute: () => AppRoute,
} as any)
const AppKhachHangRoute = AppKhachHangRouteImport.update({
  id: '/khach-hang',
  path: '/khach-hang',
  getParentRoute: () => AppRoute,
} as any)
const AppGhiChuRoute = AppGhiChuRouteImport.update({
  id: '/ghi-chu',
  path: '/ghi-chu',
  getParentRoute: () => AppRoute,
} as any)
const AppCongNoRoute = AppCongNoRouteImport.update({
  id: '/cong-no',
  path: '/cong-no',
  getParentRoute: () => AppRoute,
} as any)
const AppCoHoiRoute = AppCoHoiRouteImport.update({
  id: '/co-hoi',
  path: '/co-hoi',
  getParentRoute: () => AppRoute,
} as any)
const AppBaoGiaRoute = AppBaoGiaRouteImport.update({
  id: '/bao-gia',
  path: '/bao-gia',
  getParentRoute: () => AppRoute,
} as any)
const AppKhachHangIndexRoute = AppKhachHangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKhachHangRoute,
} as any)
const AppKhachHangCustomerIdRoute = AppKhachHangCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppKhachHangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bao-gia': typeof AppBaoGiaRoute
  '/co-hoi': typeof AppCoHoiRoute
  '/cong-no': typeof AppCongNoRoute
  '/ghi-chu': typeof AppGhiChuRoute
  '/khach-hang': typeof AppKhachHangRouteWithChildren
  '/khong-gian': typeof AppKhongGianRoute
  '/leads': typeof AppLeadsRoute
  '/luu-tru': typeof AppLuuTruRoute
  '/nguoi-dung': typeof AppNguoiDungRoute
  '/nhat-ky': typeof AppNhatKyRoute
  '/san-pham': typeof AppSanPhamRoute
  '/thu-vien': typeof AppThuVienRoute
  '/tong-quan': typeof AppTongQuanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/lp/$slug': typeof LpSlugRoute
  '/khach-hang/$customerId': typeof AppKhachHangCustomerIdRoute
  '/khach-hang/': typeof AppKhachHangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bao-gia': typeof AppBaoGiaRoute
  '/co-hoi': typeof AppCoHoiRoute
  '/cong-no': typeof AppCongNoRoute
  '/ghi-chu': typeof AppGhiChuRoute
  '/khong-gian': typeof AppKhongGianRoute
  '/leads': typeof AppLeadsRoute
  '/luu-tru': typeof AppLuuTruRoute
  '/nguoi-dung': typeof AppNguoiDungRoute
  '/nhat-ky': typeof AppNhatKyRoute
  '/san-pham': typeof AppSanPhamRoute
  '/thu-vien': typeof AppThuVienRoute
  '/tong-quan': typeof AppTongQuanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/lp/$slug': typeof LpSlugRoute
  '/khach-hang/$customerId': typeof AppKhachHangCustomerIdRoute
  '/khach-hang': typeof AppKhachHangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bao-gia': typeof AppBaoGiaRoute
  '/_app/co-hoi': typeof AppCoHoiRoute
  '/_app/cong-no': typeof AppCongNoRoute
  '/_app/ghi-chu': typeof AppGhiChuRoute
  '/_app/khach-hang': typeof AppKhachHangRouteWithChildren
  '/_app/khong-gian': typeof AppKhongGianRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/luu-tru': typeof AppLuuTruRoute
  '/_app/nguoi-dung': typeof AppNguoiDungRoute
  '/_app/nhat-ky': typeof AppNhatKyRoute
  '/_app/san-pham': typeof AppSanPhamRoute
  '/_app/thu-vien': typeof AppThuVienRoute
  '/_app/tong-quan': typeof AppTongQuanRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/lp/$slug': typeof LpSlugRoute
  '/_app/khach-hang/$customerId': typeof AppKhachHangCustomerIdRoute
  '/_app/khach-hang/': typeof AppKhachHangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bao-gia'
    | '/co-hoi'
    | '/cong-no'
    | '/ghi-chu'
    | '/khach-hang'
    | '/khong-gian'
    | '/leads'
    | '/luu-tru'
    | '/nguoi-dung'
    | '/nhat-ky'
    | '/san-pham'
    | '/thu-vien'
    | '/tong-quan'
    | '/auth/callback'
    | '/lp/$slug'
    | '/khach-hang/$customerId'
    | '/khach-hang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bao-gia'
    | '/co-hoi'
    | '/cong-no'
    | '/ghi-chu'
    | '/khong-gian'
    | '/leads'
    | '/luu-tru'
    | '/nguoi-dung'
    | '/nhat-ky'
    | '/san-pham'
    | '/thu-vien'
    | '/tong-quan'
    | '/auth/callback'
    | '/lp/$slug'
    | '/khach-hang/$customerId'
    | '/khach-hang'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/bao-gia'
    | '/_app/co-hoi'
    | '/_app/cong-no'
    | '/_app/ghi-chu'
    | '/_app/khach-hang'
    | '/_app/khong-gian'
    | '/_app/leads'
    | '/_app/luu-tru'
    | '/_app/nguoi-dung'
    | '/_app/nhat-ky'
    | '/_app/san-pham'
    | '/_app/thu-vien'
    | '/_app/tong-quan'
    | '/auth/callback'
    | '/lp/$slug'
    | '/_app/khach-hang/$customerId'
    | '/_app/khach-hang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LpSlugRoute: typeof LpSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tong-quan': {
      id: '/_app/tong-quan'
      path: '/tong-quan'
      fullPath: '/tong-quan'
      preLoaderRoute: typeof AppTongQuanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thu-vien': {
      id: '/_app/thu-vien'
      path: '/thu-vien'
      fullPath: '/thu-vien'
      preLoaderRoute: typeof AppThuVienRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/san-pham': {
      id: '/_app/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof AppSanPhamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nhat-ky': {
      id: '/_app/nhat-ky'
      path: '/nhat-ky'
      fullPath: '/nhat-ky'
      preLoaderRoute: typeof AppNhatKyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nguoi-dung': {
      id: '/_app/nguoi-dung'
      path: '/nguoi-dung'
      fullPath: '/nguoi-dung'
      preLoaderRoute: typeof AppNguoiDungRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/luu-tru': {
      id: '/_app/luu-tru'
      path: '/luu-tru'
      fullPath: '/luu-tru'
      preLoaderRoute: typeof AppLuuTruRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/khong-gian': {
      id: '/_app/khong-gian'
      path: '/khong-gian'
      fullPath: '/khong-gian'
      preLoaderRoute: typeof AppKhongGianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/khach-hang': {
      id: '/_app/khach-hang'
      path: '/khach-hang'
      fullPath: '/khach-hang'
      preLoaderRoute: typeof AppKhachHangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ghi-chu': {
      id: '/_app/ghi-chu'
      path: '/ghi-chu'
      fullPath: '/ghi-chu'
      preLoaderRoute: typeof AppGhiChuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cong-no': {
      id: '/_app/cong-no'
      path: '/cong-no'
      fullPath: '/cong-no'
      preLoaderRoute: typeof AppCongNoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/co-hoi': {
      id: '/_app/co-hoi'
      path: '/co-hoi'
      fullPath: '/co-hoi'
      preLoaderRoute: typeof AppCoHoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bao-gia': {
      id: '/_app/bao-gia'
      path: '/bao-gia'
      fullPath: '/bao-gia'
      preLoaderRoute: typeof AppBaoGiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/khach-hang/': {
      id: '/_app/khach-hang/'
      path: '/'
      fullPath: '/khach-hang/'
      preLoaderRoute: typeof AppKhachHangIndexRouteImport
      parentRoute: typeof AppKhachHangRoute
    }
    '/_app/khach-hang/$customerId': {
      id: '/_app/khach-hang/$customerId'
      path: '/$customerId'
      fullPath: '/khach-hang/$customerId'
      preLoaderRoute: typeof AppKhachHangCustomerIdRouteImport
      parentRoute: typeof AppKhachHangRoute
    }
  }
}

interface AppKhachHangRouteChildren {
  AppKhachHangCustomerIdRoute: typeof AppKhachHangCustomerIdRoute
  AppKhachHangIndexRoute: typeof AppKhachHangIndexRoute
}

const AppKhachHangRouteChildren: AppKhachHangRouteChildren = {
  AppKhachHangCustomerIdRoute: AppKhachHangCustomerIdRoute,
  AppKhachHangIndexRoute: AppKhachHangIndexRoute,
}

const AppKhachHangRouteWithChildren = AppKhachHangRoute._addFileChildren(
  AppKhachHangRouteChildren,
)

interface AppRouteChildren {
  AppBaoGiaRoute: typeof AppBaoGiaRoute
  AppCoHoiRoute: typeof AppCoHoiRoute
  AppCongNoRoute: typeof AppCongNoRoute
  AppGhiChuRoute: typeof AppGhiChuRoute
  AppKhachHangRoute: typeof AppKhachHangRouteWithChildren
  AppKhongGianRoute: typeof AppKhongGianRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppLuuTruRoute: typeof AppLuuTruRoute
  AppNguoiDungRoute: typeof AppNguoiDungRoute
  AppNhatKyRoute: typeof AppNhatKyRoute
  AppSanPhamRoute: typeof AppSanPhamRoute
  AppThuVienRoute: typeof AppThuVienRoute
  AppTongQuanRoute: typeof AppTongQuanRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBaoGiaRoute: AppBaoGiaRoute,
  AppCoHoiRoute: AppCoHoiRoute,
  AppCongNoRoute: AppCongNoRoute,
  AppGhiChuRoute: AppGhiChuRoute,
  AppKhachHangRoute: AppKhachHangRouteWithChildren,
  AppKhongGianRoute: AppKhongGianRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppLuuTruRoute: AppLuuTruRoute,
  AppNguoiDungRoute: AppNguoiDungRoute,
  AppNhatKyRoute: AppNhatKyRoute,
  AppSanPhamRoute: AppSanPhamRoute,
  AppThuVienRoute: AppThuVienRoute,
  AppTongQuanRoute: AppTongQuanRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LpSlugRoute: LpSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
